### ISSUE TITLE
프로젝트 설계(input)

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#1]
### INPUT

- 현재까지 이수한 강의
- 학번(입학년도)
- 관심있는 분야(선택형 키워드)
- 입학년도 별 졸업요건
- 전공 및 교양 강의목록

사용자로부터 어떻게 입력받는 것이 좋을까요?

**Comment by AhnYeonghoo** [comment]
이상적인건 일반적인 웹어플리케이션처럼 강의는 select로 받고, 학점이랑 과목코드, 학번, 관심 분야는 직접 입력으로 받는 것이 좋겠지만, 현실적으로는 csv나 xlsx 파일을 입력받아 전처리하고 저희가 다루기 쉬운 데이터 형태로 변환하는 게 좋긴 하겠네요.

**Comment by bokob** [comment]
* 현재까지 이수한 강의
개신누리 -> 교직/졸업 -> 수강신청을 위한 학점이수 -> 학점이수 현황에서 'Exel내보내기'로 현재까지 이수한 강의를 엑셀로 받으면 될 것 같습니다.
* 학번(입학년도)
학번은 처음 시작할 때 만약 19학번이면 19 입력하게 하면 될 것 같습니다.
* 입학년도 별 졸업요건
저희가 19~22학번의 졸업요건을 직접 조사해서 입력하면 될 것 같습니다.
* 전공 및 교양 강의목록
개신누리 -> 수업/성적 -> 수업정보 -> 개설강좌(계획서)조회에서 데이터를 추출해 만들면 될 것 같습니다.
