### ISSUE TITLE
css 적용하는 법 잘 아시는 분 있으신가요

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#106]
![image](https://user-images.githubusercontent.com/85085804/171780974-f7d08127-3141-47f5-9420-9301ee76e61a.png)

![image](https://user-images.githubusercontent.com/85085804/171781038-8f10aa30-a74a-4bff-851f-fcc304b969b4.png)

예쁜 버튼 소스를 적용하려 하는데, 잘 안되네요.

**Comment by bokob** [comment]
https://velog.io/@whdnjsdyd111/CSS-%EB%B2%84%ED%8A%BC-%EC%9D%B4%EC%81%98%EA%B2%8C-%EA%BE%B8%EB%AF%B8%EA%B8%B0

위 사진의 소스입니다.

**Comment by BiteSnail** [comment]
혹시 css파일을 안 넣으신거 아닌가요??

**Comment by AhnYeonghoo** [comment]
css 적용해도 똑같네요. 아마 css 적용 우선순위 때문에 뭘 하려고 하면 계속 꼬이는 것 같은데, 그냥 구글에서 찾은거 적용해서 적용 안되면 시도 안하는 게 나을 것 같기도 합니다..

**Comment by bokob** [comment]
조금 더 해보고 안되면 포기하겠습니다.

**Comment by bokob** [comment]
![image](https://user-images.githubusercontent.com/85085804/171801302-dca23de9-0cd8-4272-893d-a2bd1d39fc3c.png)
성공했습니다. 하지만 페이지가 잘리는 현상이 있어서 해결하고 머지하도록 하겠습니다.
