### ISSUE TITLE
홈페이지 최종 디자인 할 것들

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#107]
1. index 페이지 사진 이쁘게 보이게 하기
2. index 페이지 footer 부분 맨 아래까지 잘 정렬
3. recommand 페이지 loading delay 해결 및 이쁘게 보이게 디자인
4. 파일 업로드하고 계산하는 페이지 이쁘게 만들기

+ 추가적으로 bitesneil님이 디자인하신 학점 계산 결과 페이지는 그 디자인 그대로 쓰실거면 안 건드려도 되는건가요?

**Comment by AhnYeonghoo** [comment]
deadline 06.04 23h

**Comment by BiteSnail** [comment]
넵 원하신다면 수정하셔도 됩니다
