### ISSUE TITLE
[!!!긴급!!!] 컴퓨터공학과 신구대조과목표 가지고 계신분 공유좀 부탁드립니다.

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#12]
찾아보려고 했는데 잘 안 보여서 두분 가지고 계신 것 좀 공유 해주실 수 있나요??
부탁드립니다. ㅠㅠ

**Comment by bokob** [comment]
[전공과정_신구_대비표.pdf](https://github.com/AhnYeonghoo/opensource_project/files/8451224/_._.pdf)
한글 파일은 깃허브에서 지원이 안되어서 pdf로 변환해 올립니다.

**Comment by BiteSnail** [comment]
덕분에 살았습니다. 감사합니다 ~~
