### ISSUE TITLE
Git에서 git status 명령어 한글 깨짐 현상

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#13]
![한글깨짐](https://user-images.githubusercontent.com/85085804/162576276-3c95bc5d-6656-40cf-82f6-f91dcb8bc8c5.PNG)
t

저의 능력으로 해결이 불가능할 것 같습니다.

**Comment by BiteSnail** [comment]
git bash에서 올리실 때 한글이 깨져서 나오는 것 같은데 아래 명령어 입력해 보시면 될 것 같습니다. 저도 이걸로 해결했습니다.
git config --global core.quotepath false 
출처:
https://ssungkang.tistory.com/entry/git-%ED%95%9C%EA%B8%80-%EA%B9%A8%EC%A7%90-%ED%98%84%EC%83%81-%ED%95%B4%EA%B2%B0
