### ISSUE TITLE
신구과목대조 데이터 불러오기 문제

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#18]
### 공백데이터 출력
데이터를 불러올 때 공백도 저장되어서 불러와집니다.
![image](https://user-images.githubusercontent.com/55152597/163076963-10102a43-2fae-4a5b-b742-51cad376e6d8.png)
contrast_old_and_new.py 의 클래스 메소드에서 for문 안의 내용을 조금 손보면 해결할 수 있을 것 같습니다.
해결되면 저도 코드 올리겠습니다.

**Comment by AhnYeonghoo** [comment]
제 브랜치에 해결한 코드 push 했습니다.
