### ISSUE TITLE
강의목록출력 기능 구현 부탁드립니다.

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#21]
세부영역 또는 분야를 기준으로 하여 source/2022lecture.xlsx에서 해당하는 강의들을 출력하는 메소드 제작 부탁드립니다~
일단은 개신기초교양 영역만으로 만들어주시면 제 코드와 테스트 해보겠습니다.

**Comment by bokob** [comment]
feature_print_type_matching_info 브랜치로 푸시했습니다.
문제가 for문으로 만들어 테스트 했을 시에는 작동하는데 함수로 만들어서 테스트하면 안되는 문제가 생기네요
이 문제는 이슈로 올리겠습니다.

**Comment by bokob** [comment]
문제 해결해서 정상적으로 작동이 됩니다.
풀리퀘스트 올렸으니 확인 부탁드립니다.

**Comment by BiteSnail** [comment]
수정 된 것 확인했고 풀리퀘스트 완료하였습니다. 이슈 닫겠습니다. 감사합니다.
