### ISSUE TITLE
분야에 맞는 강의목록출력 기능 함수화 시 오류

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#22]
for문으로 따로 했을 때는 정상적으로 작동하는데
함수로 만들면 출력이 안되는 문제가 생깁니다.
도움이 필요합니다
![작동](https://user-images.githubusercontent.com/85085804/163564405-b4c2c02d-4273-4cfa-912c-a84a299eb540.PNG)
.

**Comment by AhnYeonghoo** [comment]
type 변수명을 한 번 바꿔보실래요? type이 파이썬 내장함수 이름이라서.. 물론 이게 문제라면 에러가 떠서 이게 문제일 가능성은 적긴 한데..

아니면 엑셀 파일에 정보문해 영역이 없을 수도 있구요.

쥬피터를 함수 정의부분부터 다시 처음부터 실행해보세요.

함수로 실행한 부분에 직접 '정보문해' 넣어서 어떻게 나오는지 찍어보면 어디가 문제인지 알 수도 있을 것 같네요.

**Comment by bokob** [comment]
![해결완료](https://user-images.githubusercontent.com/85085804/163657410-a678e69f-a38b-4c60-8083-66704e74ca6a.PNG)
변수명도 바꾸고
한 번에 출력하기 위해서 리스트에 출력할 목록을 넣어 그 리스트를 반환하도록 수정했습니다.
도움주셔서 감사합니다.
