### ISSUE TITLE
경로 설정 이슈

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#30]
![image](https://user-images.githubusercontent.com/77203153/166851186-5844979d-b69a-4e4c-bb31-0979c115cbdb.png)
search 디렉토리가 현재 상위폴더로부터 2단계 내려간 상태여서 ../../etc/가 맞는데
찾을 수 없다는 오류가 발생하네요.

**Comment by bokob** [comment]
models.py 기준으로 상대경로를 수정해야합니다.
