### ISSUE TITLE
추천시스템에 적용할 키워드 분류

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#32]
추천시스템에 적용할 키워드에 따른 전공 분류가 필요합니다.

e.g) 임베디드: 소프트웨어의 임베디드 시스템 과목(조희승 교수님)

**Comment by bokob** [comment]
'사람인'이라는 취업사이트 참고해서 키워드 분류 해보겠습니다.

**Comment by AhnYeonghoo** [comment]
무창이가 분류 완료
