### ISSUE TITLE
전공 키워드 분류 토의

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#34]
![image](https://user-images.githubusercontent.com/85085804/166852261-f6bd9429-542d-4a76-8659-06e335af8534.png)

직무•직업, 전문분야, 기술스택
어떤 기준으로 분류해야 좋을까요?

**Comment by AhnYeonghoo** [comment]
웹, 게임, 임베디드, 보안, 인공지능

**Comment by bokob** [comment]
게임, 네트워크 및 보안, 웹 및 앱, 임베디드, 인공지능 이렇게 분류하겠습니다.
