### ISSUE TITLE
키워드 분류표 검토 부탁드립니다.

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#36]
컴퓨터공학과 소프트웨어학부 키워드 분류한 표입니다.
컴퓨터공학과에서 겹치는 것은 소프트웨어학부에서 제외했습니다.

컴퓨터공학과 키워드
![컴공 키워드](https://user-images.githubusercontent.com/85085804/166863436-b534bba2-fd9a-4ce7-977e-12454b5706c0.PNG)

소프트웨어학부 키워드
![소웨](https://user-images.githubusercontent.com/85085804/166863467-0d475422-681d-4d46-88b0-337200262957.PNG)

**Comment by BiteSnail** [comment]
오 고생하셨습니다 ㅋㅋㅋ
이제 코드로만 옮기면 되겠네요.
어떻게 만드실건가요??

**Comment by AhnYeonghoo** [comment]
데이터베이스에 추천과목으로 넣고 키워드 클릭시 뜨도록 해보겠습니다.
