### ISSUE TITLE
교양과목 세부영역별 수강여부 출력함수 제작 부탁드립니다.

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#37]
load_data.py에 추가하기 위해서입니다. print_GE()로 만들어주시면 될 것 같습니다.

**Comment by bokob** [comment]
알겠습니다.

**Comment by bokob** [comment]
![이러케](https://user-images.githubusercontent.com/85085804/167361378-566d884c-7215-446a-b4e6-1debb0d929fb.PNG)
![성공](https://user-images.githubusercontent.com/85085804/167361402-86c95ab5-774f-4d59-8e02-cbc81759f66d.PNG)

완성했습니다. 조금 더 다듬어서 푸시하겠습니다.

**Comment by BiteSnail** [comment]
감사합니다..
