### ISSUE TITLE
기존에 정상작동하던 기능 오류 발생

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#38]
![이슈](https://user-images.githubusercontent.com/85085804/166866269-d33c5197-47b1-4912-abba-865d2813eb52.PNG)
![겟](https://user-images.githubusercontent.com/85085804/166866272-1fb45b5e-087d-48a3-b0d8-fc48420cc3df.PNG)

정현님이 실행했을 때는 정상작동하는데, 저는 안되네요.
이유를 모르겠습니다.

**Comment by BiteSnail** [comment]
dropna 문제 해결 완료하였습니다.
