### ISSUE TITLE
2019년도 2022년도 1학기 개설강의 데이터화

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#4]
19년도는 1,2학기, 계절학기 까지 그리고 22년도는 1학기까지 일단 데이터 화 해놓겠습니다.

**Comment by BiteSnail** [comment]
엑셀 파일을 만들긴 했는데 이걸 그대로 올리는 것 보다는 일반화 할 수 있는 코드를 올리는 것이 좋다고 생각합니다. 그래서 tools라는 하위 디렉토리를 만들고 거기에 제가 만든 코드를 올리려고 하는데 괜찮으십니까?
위에는 원본이고 아래는 수정본입니다...
[2019교양.xlsx](https://github.com/AhnYeonghoo/opensource_project/files/8416036/2019.xlsx)
[2019교양수정.xlsx](https://github.com/AhnYeonghoo/opensource_project/files/8416040/2019.xlsx)

**Comment by AhnYeonghoo** [comment]
엑셀 파일은 etc 폴더에 넣어서 push 안되게 하고, tools라는 폴더 만들어서 코드 올리시면 될 것 같아요. 엑셀 파일이 필요한 게 아닌 코드가 필요한거니까요. 머지하고 각자 풀하고 머지하면 될 것 같네요.

**Comment by BiteSnail** [comment]
넵 알겠습니다! 답변 감사합니다
