### ISSUE TITLE
db에 있는 파일을 파싱하여 구현한 기능대로 작동되게 만드는 작업

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#43]
사용자로부터 파일을 업로드 받아 db에 파일을 저장하는 작업까지 하였습니다. 
db에서 파일을 파싱하여 기존과 같이 동일하게 분석하여 터미널에 우선 결과를 띄우는 것 까지 

구현하면 좋을 것 같습니다.

**Comment by BiteSnail** [comment]
네 확인했습니다.
