### ISSUE TITLE
Fix require 웹서버 시작 문제

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#46]
![image](https://user-images.githubusercontent.com/55152597/167789511-5a54e16a-3c93-41ad-8b48-31cd495b25c1.png)
영후형이 올려주신 서버 파일 실행시켰는데 제대로 작동하지 않아서 이것좀 수정해주실 수 있으신가요?

**Comment by AhnYeonghoo** [comment]
search/models.py에 있는 변수 file에 csv 파일을 load하는 부분의 소스코드는 모두 삭제하고 class의 맴버함수 getter도 주석처리후 실행해도 무방합니다.

**Comment by BiteSnail** [comment]
확인 감사합니다!
