### ISSUE TITLE
git pull이 정상적으로 되지 않는 현상

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#49]
![image](https://user-images.githubusercontent.com/85085804/168406062-638917ed-9ff4-4b0a-a9cc-834da5e7a5aa.png)

![image](https://user-images.githubusercontent.com/85085804/168406183-cbb61d82-71ca-420d-831d-9e967eb904f7.png)

![image](https://user-images.githubusercontent.com/85085804/168406210-5a26f92c-e570-496c-8c56-924a50565133.png)

![image](https://user-images.githubusercontent.com/85085804/168406226-75c96758-d98e-42f3-8342-b1acb5171324.png)

반영이 안되고 있습니다.

**Comment by BiteSnail** [comment]
https://programming119.tistory.com/109

이거 한번 확인해 보시겠습니까?

**Comment by bokob** [comment]
해결완료했습니다. 감사합니다.

**Comment by BiteSnail** [comment]
푸시하신 거 확인했습니다. 감사합니다.
