### ISSUE TITLE
최저이수학점을 충족하지 못한 영역만 출력해야하는데 충족한 영역도 나오는 오류 발견

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#50]
![image](https://user-images.githubusercontent.com/85085804/168406751-45b353f4-da0b-4dae-b0a5-e4b4a7f9153f.png)

수정해주실 수 있나요?

**Comment by BiteSnail** [comment]
![image](https://user-images.githubusercontent.com/55152597/168406842-e3e7377a-e02c-4713-930a-4bb0300e3b16.png)
해결해했습니다! 다시 Pull 받으시면 될 것 같습니다.
