### ISSUE TITLE
남은 일정

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#58]
<h1>남은 일정</h1>

- 1. 다음주 중으로 로직을 웹으로 이식
- 2. README.md 수업 요구조건에 맞게 수정
- 3. 웹으로 이식하고 완성되면 PEP8에 맞게 코드 간결화 및 주석 작업
etc

**Comment by bokob** [comment]
오늘 도전하겠습니다.
