### ISSUE TITLE
지금까지 구현한 기능들을 웹에 이식하기 위한 방법 

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#59]
에 대해서 고민해보면 좋을 것 같습니다.

지금까지 구현한 로직들이 대부분 클래스로 동작하는데 

웹 API에 적용하기 위해 함수화하고, 파이썬의 list처럼 접근이 가능한지 궁금합니다.

E.g) 문사철과목[0][1] -> 이수함, 미이수함 

이런식으로

**Comment by BiteSnail** [comment]
불가능은 없습니다. 화이팅
