### ISSUE TITLE
제 pr 날린거 받아주시고, 다들 그동안 한 작업들 merge하고 각자 한 번씩 pr 날려주세요.

### ISSUE THREAD

**Issue by AhnYeonghoo** [AhnYeonghoo/opensource_project#63]
제곧내

**Comment by AhnYeonghoo** [comment]
그리고 저희가 작업한 양에 비해서 commit 수가 너무 적어요.
완성품도 중요한데 commit 60개가 만점이니.. 3줄 이상 작업한건 그때 그때 바로 commit 해야 점수 받을 수 있을 것 같아요.
그리고 pr까지 해야 contributors의 commit score가 올라갑니다.
이걸 보고 점수를 채점하시니, pr은 꼭 해주세요.

**Comment by bokob** [comment]
알겠습니다.

**Comment by BiteSnail** [comment]
네 알겠습니다
