### ISSUE TITLE
과목코드 저장 문제 도움바랍니다.

### ISSUE THREAD

**Issue by BiteSnail** [AhnYeonghoo/opensource_project#7]
pandas로 xlsx 파일을 불러올 때 dataframe에 저장될 때 정수형 데이터로 저장됩니다.  혹시 몰라서 확인해봤는데 신구대조과목 조희 때 0이 사라지면 확인할 수가 없었습니다. 앞에 0채워서 불러오거나 저장하는 방법 도움좀 요청합니다..

**Comment by bokob** [comment]
read_excel() 끝에 dtype=str 넣으면 해결이되더군요

**Comment by BiteSnail** [comment]
감사합니다. 덕분에 해결했습니다. 
저장하는 것도 csv말고 xlsx로 저장하니까 텍스트로 저장되네요. 굿굿
