### ISSUE TITLE
푸시 하신 브랜치들 이상 없으면 풀리퀘스트 부탁드립니다.

### ISSUE THREAD

**Issue by bokob** [AhnYeonghoo/opensource_project#9]
풀 해서 가져오면 브랜치들이 자동으로 안가져와져서 
하나 하나 git chekout -t origin/(브랜치) 명령어로 가져와야해서 살짝 번거롭네요.
안바쁘시다면 풀리퀘스트 해주실 수 있나요?

**Comment by BiteSnail** [comment]
확인했습니다. 빠르게 올리겠습니다.

**Comment by BiteSnail** [comment]
풀 리퀘스트 했습니다. 컨펌 부탁드리겠습니다.

**Comment by bokob** [comment]
다들 감사합니다.
